// Wave
// Copyright (C) 2025 BMDarkLight
//
// Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
// See the LICENSE file in the project root for the full license text
// and additional terms (attribution and fork-marking requirements).
// https://github.com/BMDarkLight/Wave

//! The Wave mark, rendered for a terminal, and the `wave --cli` landing
//! screen built around it.
//!
//! The art is the app icon's ribbon, generated by scripts/gen-banner-art.py
//! from the same curve as assets/app-icon.svg. It is baked in rather than
//! computed, so startup does no trigonometry. Regenerate with the script
//! rather than editing these rows by hand.

use crate::cli::render;
use crate::cli::ui::{display_width, pad, truncate, Align, Ui, ASCII};
use crate::playback_daemon::PlaybackStatus;

/// Below this width the wide mark would wrap, so the compact one is used.
pub const COMPACT_MIN_WIDTH: usize = 56;

/// Below this width even the compact mark would wrap, so only the wordmark
/// is printed.
pub const MARK_MIN_WIDTH: usize = 32;

const INDENT: usize = 2;

pub const WIDE: &[&str] = &[
    r"                               ▄▄███████▄▄▄",
    r"▄▄                         ▄▄███▀▀▀▀  ▀▀▀▀███▄",
    r"▀███▄                   ▄▄███▀              ▀███▄",
    r"  ▀▀███▄             ▄▄███▀                    ▀███▄",
    r"     ▀▀███▄▄▄   ▄▄▄████▀                          ▀█",
    r"         ▀▀███████▀▀▀",
];

pub const COMPACT: &[&str] = &[
    r"                 ▄▄█████▄▄",
    r"██▄           ▄██▀▀     ▀██▄",
    r" ▀▀██▄     ▄▄██▀           ▀██",
    r"    ▀▀█████▀▀                ▀",
];

pub const WIDE_ASCII: &[&str] = &[
    r"                               __#######___",
    r"__                         __###''''  ''''###_",
    r"'###_                   __###'              '###_",
    r"  ''###_             __###'                    '###_",
    r"     ''###___   ___####'                          '#",
    r"         ''#######'''",
];

pub const COMPACT_ASCII: &[&str] = &[
    r"                 __#####__",
    r"##_           _##''     '##_",
    r" ''##_     __##'           '##",
    r"    ''#####''                '",
];

const TAGLINE: &str = "Lightweight Music Player";

fn is_ascii(ui: &Ui) -> bool {
    ui.glyphs.ellipsis == ASCII.ellipsis
}

/// The mark plus its wordmark, sized to the terminal.
pub fn mark(ui: &Ui) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let indent = " ".repeat(INDENT);

    if ui.width < MARK_MIN_WIDTH {
        let word = truncate(
            &format!("WAVE {} {version}", ui.glyphs.dot),
            ui.width.saturating_sub(INDENT),
            ui.glyphs.ellipsis,
        );
        return format!("{indent}{}\n", ui.heading(&word));
    }

    let compact = ui.width < COMPACT_MIN_WIDTH;
    let rows = match (compact, is_ascii(ui)) {
        (false, false) => WIDE,
        (false, true) => WIDE_ASCII,
        (true, false) => COMPACT,
        (true, true) => COMPACT_ASCII,
    };
    let wordmark = if compact {
        format!("WAVE {} {version}", ui.glyphs.dot)
    } else {
        let dot = ui.glyphs.dot;
        format!("WAVE  {dot}  {TAGLINE}  {dot}  {version}")
    };

    let mut out = String::new();
    for row in rows {
        out.push_str(&indent);
        out.push_str(&ui.heading(row));
        out.push('\n');
    }
    out.push('\n');

    // Centre the wordmark under the ribbon.
    let art_width = rows.iter().map(|r| display_width(r)).max().unwrap_or(0);
    let lead = art_width.saturating_sub(display_width(&wordmark)) / 2;
    out.push_str(&" ".repeat(INDENT + lead));
    out.push_str(&ui.heading(&wordmark));
    out.push('\n');
    out
}

/// What the landing screen knows about the machine it is running on. Each
/// piece is optional, because the library may be unreadable and the daemon
/// is usually not running.
#[derive(serde::Serialize)]
pub struct LandingFacts {
    pub tracks: Option<i64>,
    pub playlists: Option<usize>,
    pub listened: Option<String>,
    pub playback: Option<PlaybackStatus>,
}

impl LandingFacts {
    /// Gather the facts, treating every failure as "unknown" rather than an
    /// error: this screen is a welcome, not a diagnostic.
    pub fn gather() -> LandingFacts {
        let library =
            crate::library::Library::new_with_path(&crate::app_paths::library_db_path()).ok();
        let playback = crate::playback_daemon::daemon_request_if_running(
            crate::playback_daemon::DaemonRequest::Status,
        )
        .ok()
        .flatten()
        .and_then(|response| response.status);

        LandingFacts {
            tracks: library.as_ref().and_then(|l| l.count_tracks().ok()),
            playlists: library
                .as_ref()
                .and_then(|l| l.list_playlists(None).ok())
                .map(|p| p.len()),
            listened: library
                .as_ref()
                .and_then(|l| l.get_listening_stats(1).ok())
                .map(|s| render::format_listen_duration(s.total_listen_seconds)),
            playback,
        }
    }
}

const LABEL_WIDTH: usize = 10;

/// A labelled line, with the value cut to whatever the terminal has left.
fn fact(ui: &Ui, label: &str, value: &str, column: usize) -> String {
    // A label longer than the column pushes the value right, so measure it.
    let label_width = display_width(label).max(column);
    let room = ui.width.saturating_sub(INDENT + label_width + 2);
    format!(
        "{}{}\n",
        " ".repeat(INDENT),
        ui.kv(
            label,
            &truncate(value, room, ui.glyphs.ellipsis),
            label_width
        )
    )
}

/// Everything on the landing screen below the mark.
pub fn landing_text(ui: &Ui, facts: &LandingFacts) -> String {
    let dot = &format!(" {} ", ui.glyphs.dot);
    let mut out = String::new();

    let mut library = Vec::new();
    if let Some(n) = facts.tracks {
        library.push(format!("{n} tracks"));
    }
    if let Some(n) = facts.playlists {
        library.push(format!("{n} playlists"));
    }
    if let Some(listened) = &facts.listened {
        library.push(format!("{listened} played"));
    }
    if !library.is_empty() {
        out.push_str(&fact(ui, "Library", &library.join(dot), LABEL_WIDTH));
    }

    if let Some(status) = &facts.playback {
        let what = match (&status.artist, &status.title) {
            (Some(artist), Some(title)) => format!("{artist}{dot}{title}"),
            (None, Some(title)) => title.clone(),
            _ => status.file.clone(),
        };
        out.push_str(&fact(
            ui,
            "Playback",
            &format!(
                "{} {what}   {} / {}",
                render::state_glyph(ui, &status.state),
                render::format_duration(status.position_seconds as u64),
                render::format_duration(status.duration_seconds as u64)
            ),
            LABEL_WIDTH,
        ));
        out.push_str(&fact(
            ui,
            "Output",
            &format!(
                "{}{dot}{}%",
                status.device,
                (status.volume * 100.0).round() as i32
            ),
            LABEL_WIDTH,
        ));
    }
    if !out.is_empty() {
        out.push('\n');
    }

    out.push_str(&format!(
        "{}{}\n",
        " ".repeat(INDENT),
        ui.heading("Getting started")
    ));
    const COMMAND_WIDTH: usize = 28;
    let command_indent = INDENT + 2;
    for (command, blurb) in [
        (
            "wave tracks import ~/Music",
            "scan a folder into the library",
        ),
        ("wave tracks list", "browse what you have"),
        ("wave play <id or name>", "play a track or playlist"),
        ("wave now", "live now-playing dashboard"),
    ] {
        let room = ui.width.saturating_sub(command_indent);
        let blurb_room = room.saturating_sub(COMMAND_WIDTH + 2);
        // On a narrow terminal the command matters more than its gloss.
        let line = if blurb_room >= 12 {
            format!(
                "{}  {}",
                pad(command, COMMAND_WIDTH, Align::Left),
                ui.dim(&truncate(blurb, blurb_room, ui.glyphs.ellipsis))
            )
        } else {
            truncate(command, room, ui.glyphs.ellipsis)
        };
        out.push_str(&format!("{}{line}\n", " ".repeat(command_indent)));
    }
    out.push('\n');

    // These two share a column of their own, wide enough for the longer
    // label, so the commands line up.
    for (label, command) in [
        ("Full reference", "wave --help"),
        ("One group", "wave tracks --help"),
    ] {
        out.push_str(&fact(ui, label, command, "Full reference".len()));
    }
    out
}

/// The landing screen without the mark, for `--no-banner`.
pub fn landing_body(ui: &Ui) -> String {
    landing_text(ui, &LandingFacts::gather())
}

/// The screen `wave --cli` shows: the mark, what is in the library, what is
/// playing, and the handful of commands worth knowing first.
pub fn landing(ui: &Ui) -> String {
    format!("\n{}\n{}", mark(ui), landing_body(ui))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::ui::{display_width, Ui, ASCII};

    fn at(width: usize) -> Ui {
        Ui {
            width,
            ..Ui::plain()
        }
    }

    fn ascii_at(width: usize) -> Ui {
        Ui {
            width,
            glyphs: ASCII,
            ..Ui::plain()
        }
    }

    fn facts() -> LandingFacts {
        LandingFacts {
            tracks: Some(1284),
            playlists: Some(9),
            listened: Some("4h 6m 1s".into()),
            playback: Some(PlaybackStatus {
                state: "playing".into(),
                file: "/music/a.flac".into(),
                position_seconds: 72.0,
                duration_seconds: 260.0,
                volume: 0.62,
                device: "MacBook Pro Speakers".into(),
                repeat: "all".into(),
                shuffle: false,
                queue_index: 1,
                queue_total: 12,
                title: Some("Once in a Lifetime".into()),
                artist: Some("Talking Heads".into()),
            }),
        }
    }

    #[test]
    fn every_tier_fits_its_declared_width() {
        for (rows, width) in [
            (WIDE, 52),
            (COMPACT, 30),
            (WIDE_ASCII, 52),
            (COMPACT_ASCII, 30),
        ] {
            for row in rows {
                assert!(display_width(row) <= width, "row too wide: {row:?}");
            }
        }
    }

    #[test]
    fn the_mark_never_overflows_the_terminal() {
        for width in [12, 20, 31, 32, 40, 55, 56, 80, 200] {
            for ui in [at(width), ascii_at(width)] {
                for line in mark(&ui).lines() {
                    assert!(
                        display_width(line) <= width,
                        "width {width} produced a {} column line: {line:?}",
                        display_width(line)
                    );
                }
            }
        }
    }

    #[test]
    fn the_tier_follows_the_width() {
        let wide = mark(&at(80)).lines().count();
        let compact = mark(&at(40)).lines().count();
        let bare = mark(&at(20)).lines().count();
        assert!(wide > compact, "wide {wide}, compact {compact}");
        // Too narrow for any art: the wordmark alone.
        assert_eq!(bare, 1);
    }

    #[test]
    fn ascii_terminals_never_get_block_characters() {
        for width in [40, 80] {
            let out = mark(&ascii_at(width));
            assert!(out.contains('#'), "width {width}");
            assert!(!out.contains('\u{2588}'), "width {width}");
            assert!(!out.contains('\u{2580}'), "width {width}");
        }
    }

    #[test]
    fn the_wordmark_carries_the_crate_version() {
        for width in [20, 40, 80] {
            assert!(mark(&at(width)).contains(env!("CARGO_PKG_VERSION")));
        }
    }

    #[test]
    fn the_landing_text_fits_the_terminal() {
        for width in [40, 60, 80, 120] {
            for line in landing_text(&at(width), &facts()).lines() {
                assert!(
                    display_width(line) <= width,
                    "width {width} produced a {} column line: {line:?}",
                    display_width(line)
                );
            }
        }
    }

    #[test]
    fn the_landing_text_omits_what_it_does_not_know() {
        let bare = LandingFacts {
            tracks: None,
            playlists: None,
            listened: None,
            playback: None,
        };
        let out = landing_text(&at(80), &bare);
        assert!(!out.contains("Library"));
        assert!(!out.contains("Playback"));
        // The getting-started commands are always worth showing.
        assert!(out.contains("wave tracks import"));
        assert!(out.contains("wave now"));
    }

    #[test]
    fn the_landing_text_reports_the_library_and_playback() {
        let out = landing_text(&at(100), &facts());
        assert!(out.contains("1284 tracks"));
        assert!(out.contains("9 playlists"));
        assert!(out.contains("Once in a Lifetime"));
        assert!(out.contains("62%"));
    }
}
